### List connectors
GET http://dockerhost:8085/connectors

### Debezium connector
POST http://dockerhost:8085/connectors
Content-Type: application/json

{
  "name": "inventory",
  "config": {
    "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
    "plugin.name": "pgoutput",
    "database.hostname": "db",
    "database.port": "5432",
    "database.user": "foo",
	"database.password": "foo",
	"database.dbname": "foo",
	"database.server.name": "no.booster",
	"schema.include.list": "inventory",
	"table.exclude.list": ""
  }
}

### Get connector status
GET http://dockerhost:8085/connectors/inventory/status

### Delete connector
DELETE http://dockerhost:8085/connectors/inventory




### Elasticsearch Sink Connector
POST http://dockerhost:8085/connectors
Content-Type: application/json

{
  "name": "elasticsearch-sink",
  "config": {
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "connection.url": "http://elasticsearch:9200",
    "tasks.max": "1",
    "topics.regex": "^books-.+$",
    "type.name": "_doc",
    "behavior.on.null.values": "DELETE",
    "schema.ignore": "true",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter"
  }
}

###

GET http://dockerhost:8085/connectors/elasticsearch-sink/status

###

DELETE http://dockerhost:8085/connectors/elasticsearch-sink
